### ISSUE TITLE
dev mode should provide lint warnings, production mode should produce errors. 

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/factorial-frontend-stack#18]
I am not sure how the linting rules are implemented here, there is no `.eslint` file that tells the IDE how to lint the JS files.

Linting on save is working strangely as well I think. When I start with `yarn start` and have linting errors, it stops the task completely until I fix all errors. Than, with no errors I can start the task again and it keeps running. But when I than reintroduce the same errors, there is no linting error and the build completes successfully.

So at the moment the only way I can see if I have linting errors or warnings is by restarting the build process with `yarn start`.

Maybe I have something configured wrong?

**Comment by mlnmln** [comment]
@krisimmig 

> I am not sure how the linting rules are implemented here, there is no .eslint file that tells the IDE how to lint the JS files.

If you want to have linting within your editor the preferred way is to use JS modules for styleltintrc and eslintrc within your project. 

```
// .stylelintrc.js
const { Neutrino } = require('neutrino');

// Specify middleware to Neutrino prior to calling stylelintrc.
// Even if using .neutrinorc.js, you must specify it when using
// the API
module.exports = Neutrino({ root: __dirname })
  .use('.neutrinorc.js')
  .call('stylelintrc');
```

```
// .eslintrc.js
const { Neutrino } = require('neutrino');

// Specify middleware to Neutrino prior to calling eslintrc.
// Even if using .neutrinorc.js, you must specify it when using
// the API
module.exports = Neutrino({ root: __dirname })
  .use('.neutrinorc.js')
  .call('eslintrc');
```

https://neutrinojs.org/packages/eslint/#eslintrc-config
https://neutrinojs.org/packages/stylelint/#stylelintrc-config

-> I'll update the docs

> Linting on save is working strangely as well I think. When I start with yarn start and have linting errors, it stops the task completely until I fix all errors. Than, with no errors I can start the task again and it keeps running. But when I than reintroduce the same errors, there is no linting error and the build completes successfully.

`start` runs in dev mode and should warn you about lint errors through the CLI. 
`build` runs in production mode and should error when there are lint errors (no successful build). 

Let me know if this is in line with your experience, otherwise please provide reproduction repo.

**Comment by mlnmln** [comment]
ok. can confirm.

**Comment by mlnmln** [comment]
See #30
